version: '3'
services:
  note-app:
    container_name: express-node-app-cont
    build:
      context: .
      args:
        - NODE_ENV=production
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    env_file:
      - ./.env    
    command: npm start  
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo-db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongo      
  redis:
    image: redis
  nginx:
    image: nginx:stable-alpine
    
    ports:
    - "8080:80"
    volumes:
      - ./nginx/deafault.conf:/etc/nginx/conf.d/deafault.conf
    depends_on: 
      - note-app
      
  

volumes:
  mongo-db:
