version: "3"
services:
  node-app:
    environment:
      - NODE_ENV=development

    container_name: express-node-app-cont
    build:
      context: .
      args:
        - NODE_ENV=development
    volumes:
      - C:\Users\Dell\node-app\src:/app/src:ro
    ports:
      - "3000:3000"
    env_file:
      - ./.env  
    command: npm run start-dev  
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
